// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDHvu7F8enB6gvb_UmL0YAO8qBdmj7ZtA',
    appId: '1:921320570425:web:ff0dec2155b78a2ed117e8',
    messagingSenderId: '921320570425',
    projectId: 'chatapp-e9be8',
    authDomain: 'chatapp-e9be8.firebaseapp.com',
    storageBucket: 'chatapp-e9be8.firebasestorage.app',
    measurementId: 'G-JZQF1KFCNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2kTLubNBNCmbILo40hfp-6WMrA7btOAY',
    appId: '1:921320570425:android:4da9df9a9c5a92e9d117e8',
    messagingSenderId: '921320570425',
    projectId: 'chatapp-e9be8',
    storageBucket: 'chatapp-e9be8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpGiAvr2rUWY0b8NG93L5N4LStqwCRzVs',
    appId: '1:921320570425:ios:f7804665f9e2d857d117e8',
    messagingSenderId: '921320570425',
    projectId: 'chatapp-e9be8',
    storageBucket: 'chatapp-e9be8.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpGiAvr2rUWY0b8NG93L5N4LStqwCRzVs',
    appId: '1:921320570425:ios:f7804665f9e2d857d117e8',
    messagingSenderId: '921320570425',
    projectId: 'chatapp-e9be8',
    storageBucket: 'chatapp-e9be8.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDHvu7F8enB6gvb_UmL0YAO8qBdmj7ZtA',
    appId: '1:921320570425:web:4579322c047be111d117e8',
    messagingSenderId: '921320570425',
    projectId: 'chatapp-e9be8',
    authDomain: 'chatapp-e9be8.firebaseapp.com',
    storageBucket: 'chatapp-e9be8.firebasestorage.app',
    measurementId: 'G-S3179ZX7FD',
  );
}
